/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TopUpImport } from './routes/top-up'
import { Route as SplatImport } from './routes/$'
import { Route as TopUpIdImport } from './routes/top-up_.$id'

// Create/Update Routes

const TopUpRoute = TopUpImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const TopUpIdRoute = TopUpIdImport.update({
  id: '/top-up_/$id',
  path: '/top-up/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/top-up': {
      id: '/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof TopUpImport
      parentRoute: typeof rootRoute
    }
    '/top-up_/$id': {
      id: '/top-up_/$id'
      path: '/top-up/$id'
      fullPath: '/top-up/$id'
      preLoaderRoute: typeof TopUpIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/top-up': typeof TopUpRoute
  '/top-up/$id': typeof TopUpIdRoute
}

export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/top-up': typeof TopUpRoute
  '/top-up/$id': typeof TopUpIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$': typeof SplatRoute
  '/top-up': typeof TopUpRoute
  '/top-up_/$id': typeof TopUpIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/top-up' | '/top-up/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/top-up' | '/top-up/$id'
  id: '__root__' | '/$' | '/top-up' | '/top-up_/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  TopUpRoute: typeof TopUpRoute
  TopUpIdRoute: typeof TopUpIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  TopUpRoute: TopUpRoute,
  TopUpIdRoute: TopUpIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$",
        "/top-up",
        "/top-up_/$id"
      ]
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/top-up": {
      "filePath": "top-up.tsx"
    },
    "/top-up_/$id": {
      "filePath": "top-up_.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
