/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GamesIndexImport } from './routes/games.index'
import { Route as GamesOrbitalFluxIndexImport } from './routes/games/orbital-flux_.index'
import { Route as GamesOrbitalFluxIdImport } from './routes/games/orbital-flux_.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GamesIndexRoute = GamesIndexImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRoute,
} as any)

const GamesOrbitalFluxIndexRoute = GamesOrbitalFluxIndexImport.update({
  id: '/games/orbital-flux_/',
  path: '/games/orbital-flux/',
  getParentRoute: () => rootRoute,
} as any)

const GamesOrbitalFluxIdRoute = GamesOrbitalFluxIdImport.update({
  id: '/games/orbital-flux_/$id',
  path: '/games/orbital-flux/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexImport
      parentRoute: typeof rootRoute
    }
    '/games/orbital-flux_/$id': {
      id: '/games/orbital-flux_/$id'
      path: '/games/orbital-flux/$id'
      fullPath: '/games/orbital-flux/$id'
      preLoaderRoute: typeof GamesOrbitalFluxIdImport
      parentRoute: typeof rootRoute
    }
    '/games/orbital-flux_/': {
      id: '/games/orbital-flux_/'
      path: '/games/orbital-flux'
      fullPath: '/games/orbital-flux'
      preLoaderRoute: typeof GamesOrbitalFluxIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesIndexRoute
  '/games/orbital-flux/$id': typeof GamesOrbitalFluxIdRoute
  '/games/orbital-flux': typeof GamesOrbitalFluxIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesIndexRoute
  '/games/orbital-flux/$id': typeof GamesOrbitalFluxIdRoute
  '/games/orbital-flux': typeof GamesOrbitalFluxIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/games/': typeof GamesIndexRoute
  '/games/orbital-flux_/$id': typeof GamesOrbitalFluxIdRoute
  '/games/orbital-flux_/': typeof GamesOrbitalFluxIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games' | '/games/orbital-flux/$id' | '/games/orbital-flux'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games' | '/games/orbital-flux/$id' | '/games/orbital-flux'
  id:
    | '__root__'
    | '/'
    | '/games/'
    | '/games/orbital-flux_/$id'
    | '/games/orbital-flux_/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GamesOrbitalFluxIdRoute: typeof GamesOrbitalFluxIdRoute
  GamesOrbitalFluxIndexRoute: typeof GamesOrbitalFluxIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  GamesOrbitalFluxIdRoute: GamesOrbitalFluxIdRoute,
  GamesOrbitalFluxIndexRoute: GamesOrbitalFluxIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/games/",
        "/games/orbital-flux_/$id",
        "/games/orbital-flux_/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/games/": {
      "filePath": "games.index.tsx"
    },
    "/games/orbital-flux_/$id": {
      "filePath": "games/orbital-flux_.$id.tsx"
    },
    "/games/orbital-flux_/": {
      "filePath": "games/orbital-flux_.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
